### ISSUE TITLE
Small memleak in button_demoReel100.ino

### ISSUE THREAD

**Issue by costyn** [atuline/FastLED-Demos#14]
I fixed a small memleak in my fork. I tried to create a pull request "back to your code", but I haven't figured out github completely yet.

https://github.com/costyn/FastLED-Demos/commit/f24978cdd89ef469660967dda76d27cdebc69059

**Comment by atuline** [comment]
I'm not too good at it either. I just edited my own code and updated manually. I really need to get back into this.

**Comment by marmilicious** [comment]
Aaah, the writing to non-existent pixel pickle!  Good catch @costyn.
