### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by apriest2** [atuline/FastLED-Demos#19]
I'm fairly new to programming, I have run through almost all of your demos to help me understand how to program LEDS, and I have gotten almost all of your other demos to work. But with this demo I am having compiling errors. Any ideas how I can fix this? Sorry I'm very new to programming, but it's something that I'd like to try and I like working with LEDS cause they are fun!

**Comment by atuline** [comment]
Most of the demos in here should work without a problem if you have installed FastLED correctly. Some of them (and you didn't mention which one you're having problems with), such as seirlight or fht_log require 3rd party libraries to be downloaded and installed. I would recommend avoiding those until you get more experience. In the meantime, here's some general FAQ stuff:

http://tuline.com/fastled-support-qa/

**Comment by apriest2** [comment]
Sorry I didn't mention which demo I was working through. I was working
through the button_demoReel100. I'm using WS2812 LEDS, and an arduino Pro
Trinket  Atmega328P micro controller. I downloaded and installed the needed
libraries, including the https://github.com/JChristensen/Button library.
I haven't tried the seirlight demos yet, because I read that they are more
difficult. Every other demo I've tried has worked, and this isn't my first
demo that uses a 3rd party library.

Thank you so much for getting back to me so quickly, I apologize that I
don't have the experience to know what is going wrong.


Andrew

**Comment by atuline** [comment]
In the case of button_demoReel100, I no longer use the JChristensen button library as I found it more complex to use and with less functionality than the jsbutton.h that's included with this sketch. I'm wondering if there's some form of overlap.

As for a Trinket, I haven't tried those out, and primarily just use Nano's and UNO's.
