### ISSUE TITLE
Separate channels

### ISSUE THREAD

**Issue by chuco61** [atuline/FastLED-Demos#20]
How can this be modified so that the bands of color can be broken  out to separate pins in order to create a color organ?

**Comment by marmilicious** [comment]
Can you provide more info and specifics about what you're asking about?

**Comment by atuline** [comment]
Hi Marc,  I've been in touch with him via email and he wanted to make a traditional colour organ. I've since directed him towards WS2812's/APA102's and the FHT library. Have also shown him some other sound reactive routines.
