### ISSUE TITLE
ripples.ino is not compiling.

### ISSUE THREAD

**Issue by kidkill** [atuline/FastLED-Demos#28]
I'm getting the error 

> ISO C++ forbids declaration of 'Move' with no type [-fpermissive]

**Comment by atuline** [comment]
These routines were developed and tested on a Nano/UNO. I'm slowly working to test them against an ESP8266, which I assume you're compiling for. This ripples.ino file contains code I'd inherited (see comments at top). Change line 60 from 'Move() {' to 'void Move() {'. Do the same for line 83. I'll slowly get around to fixing these.

Some of my other routines, in particular notamesh and notasound may require some work to get them up to speed. In particular, I need to change the EEPROM code.
