### ISSUE TITLE
easing

### ISSUE THREAD

**Issue by smoochiee** [atuline/FastLED-Demos#29]
effects doesnt loop

**Comment by atuline** [comment]
Just successfully tested the easing demo on an ESP8266 (was originally written for a Nano). LED should start at leds[0] slowly, speed up, and slow down again as it approaches leds[NUM_LEDS-1]. Then it should start again from leds[0].

If you have modified the code, you may want to check that. If you would like any support for changes you may have made, post your code on pastebin.com and submit a Q on https://www.reddit.com/r/FastLED/ with a link to your code. Also post a link to the original, which is at https://github.com/atuline/FastLED-Demos/tree/master/easing.
