### ISSUE TITLE
What's the proper way to chain the effects one after another?

### ISSUE THREAD

**Issue by shenkev** [atuline/FastLED-Demos#4]
I'm not sure how to use EVERY_N_MILLISECONDS(thisdelay) when I want to do an effect for 5 seconds, then do another effect for 5 seconds

**Comment by atuline** [comment]
You could use EVERY_N_SECONDS(thisdelay) for that, but will need to add code to change the routine.

I don't use that method, rather, I use:

https://github.com/atuline/FastLED-Demos/blob/master/one_sine_pal_demo/one_sine_pal_demo.ino

This is the bigger and more complex one:

https://github.com/atuline/FastLED-Demos/tree/master/aalight

**Comment by shenkev** [comment]
Not really an extension of the issue, but I was wondering if you could point me in the right direction on 2 design I have in mind. Any help would be greatly appreciated! I'm going to have a LED strand in an elliptical shape.
- I believe the term is a "chaser" but I want to have a color move around the ellipse like a track-n-field runner. The color starts at yellow, then becomes orange then red, sort of like a fire.
- If the track is 400m, I want two "sinks" at 50m and 250m (on the long diameter ends) and I want color to flow into the sinks sort of like lava. So LEDs at 350-50m and 50-150 meters would flow into the 50m sink. LEDs at 150 to 250 and 250 to 350 would flow into the 250m sink.

I think you've implemented similar methods to the first idea but I couldn't figure out how to transform your implementation exactly into what I want. What FastLED API  methods should I look into for my ideas? Thank you!

**Comment by atuline** [comment]
Your best best for ideas and general support is at:

https://plus.google.com/communities/109127054924227823508

As for using colours, I just define and use palettes for the most part. My recommendation would be to find all the demos you can get and learn from them. There's a lot out there on gist.github.com and pastebin.com.
