### ISSUE TITLE
Multiple Strips

### ISSUE THREAD

**Issue by xklob** [atuline/FastLED-Demos#5]
I've gotten this to work well enough on a single strip; however, I have 4 led strips in my room, one on each border wall of the ceiling. I tried adding all strips to a single LED array, but for some reason that didn't work.

Is there any way to make multiple strips on multiple pins work?

**Comment by xklob** [comment]
Actually, I resolved this. I wasn't adding strips 2, 3, and 4 to the right locations in the array.

**Comment by atuline** [comment]
Glad to hear! In the meantime . . as I recall, multiple strips on multiple pins should work with WS2812, but not with APA102 strips. Since my projects are all small, I just break up into multiple strips, but still connect Dout from strip1 to Din of strip2.
