### ISSUE TITLE
Auto Mode Cycle

### ISSUE THREAD

**Issue by LedArts** [atuline/FastLED-Demos#6]
hello sir,
I need a Function to run all the effects one by one. Like auto mode cycle function.

**Comment by atuline** [comment]
One method is:

https://github.com/FastLED/FastLED/blob/master/examples/DemoReel100/DemoReel100.ino

Here's a nice modification to the above he did that supports arguments for each demo at:

https://gist.github.com/kriegsman/536dd5f2238413cf0ee2


In my case, I use aalight.ino at:

https://github.com/atuline/FastLED-Demos/tree/master/aalight

Of course, modifying any of these requires that you are already very familiar with Arduino coding.

**Comment by LedArts** [comment]
thank you sir, 
i Familiar with C and C++ coding. i don't know how how to modify arduino program. Actually i am confused that in which software arduino program can be modified AVR Studio or Arduino IDE.
i want to add more effects of ws2811 led strip.

**Comment by LedArts** [comment]
i see aalight.ino prgoram and i want to add more effects.
