### ISSUE TITLE
How to Add More Effects in program

### ISSUE THREAD

**Issue by LedArts** [atuline/FastLED-Demos#7]
thank you sir,
i Familiar with C and C++ coding. i don't know how how to modify arduino program. Actually i am confused that in which software arduino program can be modified AVR Studio or Arduino IDE.
i want to add more effects of ws2811 led strip.
i see aalight.ino prgoram and i want to add more effects.

**Comment by atuline** [comment]
It’s good that you already know C and C++, however, I think you’ll need to teach yourself/learn the basic of using Arduino’s before you can add more effects to aalight.

 

I use the Arduino software available at:

 

https://www.arduino.cc/en/Main/Software

**Comment by LedArts** [comment]
sir, i am already using arduino for pixel led. i have fast led library and also u r's fast led demos master library. and i have add it in my arduino software now please tech me how to add more effects in aalight.ino

**Comment by atuline** [comment]
Since you are already familiar with C and C++, you should already have the knowledge to modify these files.

If not, my recommendation is to start with the simple routines, modify them and slowly build up from there.

**Comment by LedArts** [comment]
sir only tell me in which software i should edit this program- avr studio or arduino.
i am confused because .h file is not open in arduino if i have to edit .h file then what should i do.
and also tell me should i edit .h file or any other file to add the effect or directly i can make effects in aalight.ino file

**Comment by atuline** [comment]
I use the Arduino IDE available at https://www.arduino.cc/en/Main/Software

It will also open .h files, which I use to separate out the effects from all of the support code.

If you're looking for something simpler, I highly recommend this instead:

https://github.com/FastLED/FastLED/blob/master/examples/DemoReel100/DemoReel100.ino

**Comment by atuline** [comment]
Furthermore, if you're not even at the stage of running and modifying basic Arduino sketches, then attempting to modify the aalight.ino and included .h files is a few steps beyond.

**Comment by LedArts** [comment]
ok sir thank you,
i will try this.
please tell me if i want to add cylon effect in demoreel 100 which things should i know?


void rainbow() 
{
  // FastLED's built-in rainbow generator
  fill_rainbow( leds, NUM_LEDS, gHue, 7);
}

void rainbowWithGlitter() 
{
  // built-in FastLED rainbow, plus some random sparkly glitter
  rainbow();
  addGlitter(80);
} 

In these two functions they call function and no.s only. means this are inbuilt in fast led library.

can u guild me to make any function or effect in demo reel 100 or give me any tutorial which helpful for me

**Comment by atuline** [comment]
There's lots of demos available at:

https://github.com/FastLED/FastLED/tree/master/examples
https://github.com/marmilicious/FastLED_examples
https://github.com/atuline/FastLED-Demos

My recommendation is that you compile, study and change them and see what happens.

FastLED documentation is at:
https://github.com/FastLED/FastLED/wiki/Basic-usage

Code for FastLED is at:
https://github.com/FastLED/FastLED

There's additional FastLED documentation buried in the code.

**Comment by LedArts** [comment]
ok sir thanks a lot
