### ISSUE TITLE
fast led demo master not valid library???

### ISSUE THREAD

**Issue by LedArts** [atuline/FastLED-Demos#8]
sir i try to add fast led demo master library but ardiuno shows the error-Specified folder/zip file does not contain a valid library
what should i do

**Comment by LedArts** [comment]
sir i directly open aalight.ino but it gives error button library not included please give me the button library also....

**Comment by LedArts** [comment]
oops sorry i got the button library in your code

**Comment by atuline** [comment]
I assume you got the FastLED library running. Please keep in mind that you need to already have FastLED running PRIOR to using my examples. In addition, aalight.ino is a more advanced sketch and you should be running the others first and to be able to write your own before attempting that one.

**Comment by LedArts** [comment]
yes sir i have already fast led library. thank you sir.
as your advice i am doing it from small and simple examples. i just want to see aalight effect thats why i try it.
